---
- name: Install Ruby dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - libreadline-dev
    - libssl-dev
    - libyaml-dev
    - zlib1g-dev

- name: Download the Ruby source code
  get_url: url=http://ftp.ruby-lang.org/pub/ruby/2.0/ruby-{{ ruby_version }}.tar.bz2
           dest=/usr/local/src/
           sha256sum={{ ruby_checksum }}

- name: Generate the Ruby installation script on the server
  template: src=install-ruby.j2
            dest=/usr/local/src/install-ruby.sh
            mode=700

- name: Run the Ruby installation script
  command: /usr/local/src/install-ruby.sh
           creates={{ ruby_location }}/bin/ruby

- name: Generate the wrapper script that contains GC settings
  template: src=ruby-gc-wrapper.j2
            dest=/usr/local/bin/ruby-gc-wrapper
            mode=755

- name: Generate the script that allows us to easily run Rake tasks with RAILS_ENV set to production
  template: src=rake-production.j2
            dest=/usr/local/bin/rake-production
            mode=755

- name: Install Bundler
  command: "{{ ruby_location }}/bin/gem install bundler 
            creates={{ ruby_location }}/bin/bundle"

- name: Make Ruby symlinks
  file: path=/usr/local/bin/{{ item }}
        src={{ ruby_location }}/bin/{{ item }}
        state=link
  with_items:
    - bundle
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ri
    - ruby
